// The fixed page addresses of the manual (section 3 of the brief). They are a contract: the
// FAIVR store docs link to them. Add an address here when a page is added; never remove one
// without a redirect in astro.config.mjs.
export const REQUIRED_PAGES = [
  '/',
  '/start/member/',
  '/start/roles/',
  '/start/glossary/',
  '/setup/unbox-and-connect/',
  '/setup/first-run/',
  '/setup/ai-providers/',
  '/setup/budget/',
  '/setup/members/',
  '/setup/connections/',
  '/setup/store-enrolment/',
  '/setup/first-agent/',
  '/setup/backup/',
  '/setup/remote-access/',
  '/use/start-a-task/',
  '/use/follow-a-run/',
  '/use/phone-and-voice/',
  '/use/approvals-and-checks/',
  '/use/knowledge/',
  '/use/workboard/',
  '/use/report-a-problem/',
  '/use/your-account/',
  '/admin/agent-rules/',
  '/admin/users/',
  '/admin/administrator-password/',
  '/admin/packages/',
  '/admin/store/',
  '/admin/products-and-knowledge/',
  '/admin/ai-providers-and-lanes/',
  '/admin/budget/',
  '/admin/connections/',
  '/admin/autonomy-levels/',
  '/admin/backup-and-restore/',
  '/admin/updates/',
  '/admin/remote-access/',
  '/admin/audit-and-status/',
  '/agents/',
  '/agents/software-delivery/',
  '/agents/product-ownership/',
  '/agents/website-care/',
  '/agents/design-review/',
  '/agents/marketing-planning/',
  '/agents/strategy-and-challenge/',
  '/agents/pricing-and-business-models/',
  '/agents/visibility-in-ai-search/',
  '/agents/linkedin-posting/',
  '/not-yet/',
  '/troubleshooting/',
  '/releases/',
];

// Pages that link to the FAIVR store docs, with the exact addresses they must contain.
export const REQUIRED_LINKS = {
  '/setup/store-enrolment/': ['https://faivr.ai/docs/how-buying-works', 'https://faivr.ai/docs/billing', 'https://faivr.ai/docs/cancel'],
  '/admin/store/': ['https://faivr.ai/docs/how-buying-works', 'https://faivr.ai/docs/billing', 'https://faivr.ai/docs/cancel'],
  '/admin/packages/': ['https://faivr.ai/docs/trust'],
  '/agents/software-delivery/': ['https://faivr.ai/catalog/software-delivery'],
  '/agents/product-ownership/': ['https://faivr.ai/catalog/product-ownership'],
  '/agents/website-care/': ['https://faivr.ai/catalog/website-care'],
  '/agents/design-review/': ['https://faivr.ai/catalog/design-review'],
  '/agents/marketing-planning/': ['https://faivr.ai/catalog/marketing-planning'],
  '/agents/strategy-and-challenge/': ['https://faivr.ai/catalog/strategy-and-challenge'],
  '/agents/pricing-and-business-models/': ['https://faivr.ai/catalog/pricing-and-business-models'],
  '/agents/visibility-in-ai-search/': ['https://faivr.ai/catalog/visibility-in-ai-search'],
  '/agents/linkedin-posting/': ['https://faivr.ai/catalog/linkedin-posting'],
};

// Old addresses that moved, with their new address. Each must stay in public/_redirects (301)
// and in `redirects` in astro.config.mjs. Never remove a line.
export const MOVED_PAGES = {
  '/workers/': '/agents/',
  '/workers/software-delivery/': '/agents/software-delivery/',
  '/workers/product-ownership/': '/agents/product-ownership/',
  '/workers/website-care/': '/agents/website-care/',
  '/workers/design-review/': '/agents/design-review/',
  '/workers/marketing-planning/': '/agents/marketing-planning/',
  '/workers/strategy-and-challenge/': '/agents/strategy-and-challenge/',
  '/workers/pricing-and-business-models/': '/agents/pricing-and-business-models/',
  '/workers/visibility-in-ai-search/': '/agents/visibility-in-ai-search/',
  '/workers/linkedin-posting/': '/agents/linkedin-posting/',
  '/setup/first-worker/': '/setup/first-agent/',
  '/operator/chatgpt-personal-plan/': '/setup/ai-providers/',
};
