// Writes src/content/docs/not-yet.mdx from the gap table in docs/content-inventory.md
// (section "Gaps"), so the page and the inventory always list the same gaps.
//   node scripts/sync-not-yet.mjs          writes the page
//   node scripts/sync-not-yet.mjs --check  fails when the page is out of date
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const inventoryFile = `${root}docs/content-inventory.md`;
const pageFile = `${root}src/content/docs/not-yet.mdx`;

const rows = readFileSync(inventoryFile, 'utf8')
  .split('\n')
  .filter(line => /^\| G\d+ \|/.test(line))
  .map(line => line.trim().replace(/^\||\|$/g, '').split('|').map(cell => cell.trim()));
if (!rows.length) {
  console.error('sync-not-yet: no gap rows (lines starting with "| G<number> |") found in the inventory');
  process.exit(1);
}

const areas = new Map();
for (const [id, area, gap, workaround, who] of rows) {
  if (!who) {
    console.error(`sync-not-yet: gap ${id} needs five columns: # | Area | Gap | Workaround today | Who to ask`);
    process.exit(1);
  }
  if (!areas.has(area)) areas.set(area, []);
  areas.get(area).push({ gap, workaround, who });
}

const lines = [
  '---',
  'title: Not possible yet',
  'description: Everything an administrator or member might expect but cannot do in this release, with what to do instead and who to ask.',
  '---',
  "import SupportContact from '~/components/SupportContact.astro';",
  '',
  '{/* Generated from docs/content-inventory.md by scripts/sync-not-yet.mjs. Do not edit this file by hand: edit the inventory, then run npm run sync:not-yet. */}',
  '',
  'Each item says what to do instead today and who to ask. "Administrator" means the CEO administrator of your box. "Support" means the contact below.',
  '',
  '**Support contact:** <SupportContact />',
];
for (const [area, items] of areas) {
  lines.push('', `## ${area}`, '', '| Not possible yet | What to do instead | Who to ask |', '| --- | --- | --- |');
  for (const { gap, workaround, who } of items) lines.push(`| ${gap} | ${workaround} | ${who} |`);
}
lines.push('', '## Related pages', '', '- [Troubleshooting](/troubleshooting/)', '- [Report a problem](/use/report-a-problem/)', '');
const page = lines.join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(pageFile, 'utf8'); } catch { /* missing counts as out of date */ }
  if (current !== page) {
    console.error('sync-not-yet: src/content/docs/not-yet.mdx is out of date. Run: npm run sync:not-yet');
    process.exit(1);
  }
  console.log(`sync-not-yet: the page lists the same ${rows.length} gaps as the inventory`);
} else {
  writeFileSync(pageFile, page);
  console.log(`sync-not-yet: wrote ${rows.length} gaps in ${areas.size} areas`);
}
